Repository crislinfrajo/WeatherAnalytics, pull requests merged in 2021-03, with the labels that each got.

#8 gitignore added node_modules
  .gitignore
Labels: enhancement

#9 Cristina/user stories
  README.md
  agil.yaml
Labels: user-stories

#11 Tools and Technologies close #10
  README.md
Labels: documentation

#13 Cristina/add solution
  README.md
Labels: documentation

#15 add log to readme file
  README.md
Labels: documentation
